### ISSUE TITLE
feat: add support for SM 1.12

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/docker-sourceknight#1]
https://github.com/sbpp/sourcebans-pp/pull/1003

```
Error occurred during unpack, removing build tree...
Traceback (most recent call last):
  File "/usr/local/bin/sourceknight", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/sourceknight/main.py", line 44, in main
    command(ctx)(args)
  File "/usr/local/lib/python3.10/site-packages/sourceknight/build.py", line 28, in __call__
    unpack(self._ctx)(args)
  File "/usr/local/lib/python3.10/site-packages/sourceknight/unpack.py", line 38, in __call__
    dmgr.unpack(self._ctx._state.dependencies[dep['name']], dep['unpack'], fmgr, args.force)
  File "/usr/local/lib/python3.10/site-packages/sourceknight/dependencies.py", line 63, in unpack
    drivers_by_name[d.params['driver']](self._ctx, d).unpack(fmgr, locations)
  File "/usr/local/lib/python3.10/site-packages/sourceknight/drivers/tar.py", line 28, in unpack
    with tarfile.open(os.path.join(self._ctx._path, self._model.params['location'])) as tar:
  File "/usr/local/lib/python3.10/tarfile.py", line [18](https://github.com/sbpp/sourcebans-pp/actions/runs/11755379771/job/32750386124?pr=1003#step:4:19)04, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('truncated header')
```

**Comment by maximee-leroyy** [comment]
i think you just made a typo thats why:
- https://github.com/sbpp/sourcebans-pp/pull/1003/files#r1835335686
